# Generated by Django 5.0.4 on 2024-05-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=2, max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
